config/routes.rb
Rails.application.routes.draw do
  root :to => "homes#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # resources :homes, only: [:index, :new, :create]
  resources :homes do
    post :bulk_add_data, on: :collection
  end  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hospital_datum.rb
class HospitalDatum < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def index
    @hospital_data = HospitalDatum.all
  end

  def new
    @hospital_data = HospitalDatum.new
  end

  def create
    @hospital_data = HospitalDatum.new(params_data)

    if @hospital_data.save
      redirect_to root_path
    else
      render :new
    end
  end

  def bulk_add_data
    file = params[:xml_file]
    xlsx = Roo::Spreadsheet.open(file, extension: :xlsx)
    count = xlsx.count
    for i in 1...count do
      hospital_name = xlsx.row(i+1)[0]
      oxygen_can = xlsx.row(i+1)[1]
      bed = xlsx.row(i+1)[2]

      @hospital_data = HospitalDatum.new(name: hospital_name, oxygen_can: oxygen_can, bed: bed)
      @hospital_data.save
    end
    redirect_to root_path
  end

  private

  def params_data 
    params.require(:hospital_datum).permit(:name, :oxygen_can, :bed)
    # params.permit(:name, :oxygen_can, :bed)

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/homes/index.html.erb
<%= link_to 'Add new', new_home_path %>

<div class="">
    <div class="row">
        <h3 class="col-md-3 item1"> Index </h3>
        <h3 class="col-md-3 item1"> Hospital Name </h3>
        <h3 class="col-md-3 item1"> Oxygen Cans </h3>
        <h3 class="col-md-3 item1"> No. of Beds </h3>
    </div>


    <% @hospital_data.each do |data| %>
        <div class="row">
            <p class="col-md-3 item1"> 1 </p>
            <p class="col-md-3 item1"><%=  data.name %> </p>
            <p class="col-md-3 item1"><%= data.oxygen_can %> </p>
            <p class="col-md-3 item1"><%= data.bed %> </p>
        </div>
    <% end %>
</div>

app/views/homes/new.html.erb
<div class="container">
		<%= form_tag(bulk_add_data_homes_path,  multipart: true, class: 'btn btn-primary btn-sm pull-right custom-export-button') do %>
			<%#= file_field :files, name: 'attachment[file]', id: 'file-input'%>
			<%= file_field_tag 'xml_file' %>
			<%= submit_tag 'OK', class: 'btn btn-secondary' %>
		<% end %>
</div>

<%= form_for @hospital_data, url: homes_path, method: :post do |f| %>
	<div class="container">
		<div class="row">
			<%= f.label :name,'Hospital Name', class: 'col-md-3'%>
			<%= f.text_field :name, class: 'col-md-3' %>
		</div>

		<div class="row">
			<%= f.label :name,'Oxygen Concentrators', class: 'col-md-3'%>
			<%= f.text_field :oxygen_can, class: 'col-md-3' %>
		</div>

		<div class="row">
			<%= f.label :name,'Beds', class: 'col-md-3'%>
			<%= f.text_field :bed, class: 'col-md-3' %>
		</div>
		
		<div class="row">
			<%= f.submit 'Add Data', class: 'btn btn-primary col-sm-2' %>
			<%= link_to 'Back', homes_path, class: 'btn btn-primary col-sm-2' %>
		</div>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CovidHelp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>

  <body>
  <!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <%= yield %>
  </body>
</html>